; timestamp: 20220306T210748Z
; source id: tld-query-td.-pch.nic.td.
; source locator: pch.nic.td.
; source IP address: 204.61.216.129
; backup point IP address: 111.42.148.76
; status: success
td.			7200	IN	NS	pch.nic.td.td.			7200	IN	NS	anycastdns1.nic.td.td.			7200	IN	NS	ns-td.afrinic.net.td.			7200	IN	NS	anycastdns2.nic.td.pch.nic.td.		3600	IN	A	204.61.216.129pch.nic.td.		1382	IN	AAAA	2001:500:14:6129:ad::1