; timestamp: 20220306T211341Z
; source id: tld-query-ua.-rcz.ns.ua.
; source locator: rcz.ns.ua.
; source IP address: 193.46.128.10
; backup point IP address: 111.42.148.76
; status: success
ua.			3598	IN	NS	ho1.ns.ua.ua.			3598	IN	NS	in1.ns.ua.ua.			3598	IN	NS	rcz.ns.ua.ua.			3598	IN	NS	pch.ns.ua.ua.			3598	IN	NS	cd1.ns.ua.ua.			3598	IN	NS	bg.ns.ua.rcz.ns.ua.		3558	IN	A	193.46.128.10rcz.ns.ua.		3558	IN	AAAA	2a02:850:ffe0::10