; timestamp: 20220306T211012Z
; source id: tld-query-tl.-ns.anycast.nic.tl.
; source locator: ns.anycast.nic.tl.
; source IP address: 204.61.216.19
; backup point IP address: 111.42.148.76
; status: success
tl.			86400	IN	NS	ns.anycast.nic.tl.tl.			86400	IN	NS	ns2.anycastdns.cz.tl.			86400	IN	NS	ns1.anycastdns.cz.ns.anycast.nic.tl.	3600	IN	A	204.61.216.19ns.anycast.nic.tl.	3600	IN	AAAA	2001:500:14:6019:ad::1