; timestamp: 20220306T211341Z
; source id: tld-query-ua.-ho1.ns.ua.
; source locator: ho1.ns.ua.
; source IP address: 195.47.253.1
; backup point IP address: 111.42.148.76
; status: success
ua.			3600	IN	NS	pch.ns.ua.ua.			3600	IN	NS	cd1.ns.ua.ua.			3600	IN	NS	ho1.ns.ua.ua.			3600	IN	NS	bg.ns.ua.ua.			3600	IN	NS	rcz.ns.ua.ua.			3600	IN	NS	in1.ns.ua.ho1.ns.ua.		3560	IN	A	195.47.253.1ho1.ns.ua.		3559	IN	AAAA	2001:67c:258::1