; timestamp: 20220306T201228Z
; source id: tld-query-gr.-gr-m.ics.forth.gr.
; source locator: gr-m.ics.forth.gr.
; source IP address: 194.0.4.10
; backup point IP address: 111.42.148.76
; status: success
gr.			10800	IN	NS	gr-m.ics.forth.gr.gr.			10800	IN	NS	estia.ics.forth.gr.gr.			10800	IN	NS	gr-at.ics.forth.gr.gr.			10800	IN	NS	grdns.ics.forth.gr.gr.			10800	IN	NS	gr-c.ics.forth.gr.gr.			10800	IN	NS	gr-d.ics.forth.gr.gr-m.ics.forth.gr.	3600	IN	A	194.0.4.10gr-m.ics.forth.gr.	3600	IN	AAAA	2001:678:7::4:10