; timestamp: 20220306T210038Z
; source id: tld-query-sk.-h.tld.sk.
; source locator: h.tld.sk.
; source IP address: 212.18.249.16
; backup point IP address: 111.42.148.76
; status: success
sk.			329	IN	NS	g.tld.sk.sk.			329	IN	NS	c.tld.sk.sk.			329	IN	NS	b.tld.sk.sk.			329	IN	NS	e.tld.sk.sk.			329	IN	NS	f.tld.sk.sk.			329	IN	NS	h.tld.sk.sk.			329	IN	NS	a.tld.sk.h.tld.sk.		3587	IN	A	212.18.249.16h.tld.sk.		3587	IN	AAAA	2a04:2b00:13ff::16