; timestamp: 20220306T201745Z
; source id: tld-query-inc.-c.nic.inc.
; source locator: c.nic.inc.
; source IP address: 212.18.248.137
; backup point IP address: 111.42.148.76
; status: success
dig @212.18.248.137 inc. NS

; <<>> DiG 9.16.23 <<>> @212.18.248.137 inc. NS
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

c.nic.inc.		3566	IN	A	212.18.248.137c.nic.inc.		3566	IN	AAAA	2a04:2b00:13ee::137