; timestamp: 20220306T195854Z
; source id: tld-query-cy.-estia.ics.forth.gr.
; source locator: estia.ics.forth.gr.
; source IP address: 139.91.191.3
; backup point IP address: 111.42.148.76
; status: success
cy.			7200	IN	NS	ns31.rcode0.net.cy.			7200	IN	NS	ns4.apnic.net.cy.			7200	IN	NS	cynic6.dns.cy.cy.			7200	IN	NS	estia.ics.forth.gr.cy.			7200	IN	NS	cy-ns.anycast.pch.net.cy.			7200	IN	NS	cynic4.dns.cy.estia.ics.forth.gr.	3600	IN	A	139.91.191.3estia.ics.forth.gr.	3518	IN	AAAA	2001:648:2c30::191:3