; timestamp: 20220306T210748Z
; source id: tld-query-td.-anycastdns1.nic.td.
; source locator: anycastdns1.nic.td.
; source IP address: 185.38.108.108
; backup point IP address: 111.42.148.76
; status: success
td.			3600	IN	NS	ns-td.afrinic.net.td.			3600	IN	NS	anycastdns2.nic.td.td.			3600	IN	NS	pch.nic.td.td.			3600	IN	NS	anycastdns1.nic.td.anycastdns1.nic.td.	600	IN	A	185.38.108.108anycastdns1.nic.td.	3600	IN	AAAA	2a00:fea0:dead::beef