; timestamp: 20220306T210038Z
; source id: tld-query-sk.-g.tld.sk.
; source locator: g.tld.sk.
; source IP address: 212.18.248.16
; backup point IP address: 111.42.148.76
; status: success
sk.			86400	IN	NS	g.tld.sk.sk.			86400	IN	NS	a.tld.sk.sk.			86400	IN	NS	e.tld.sk.sk.			86400	IN	NS	h.tld.sk.sk.			86400	IN	NS	b.tld.sk.sk.			86400	IN	NS	c.tld.sk.sk.			86400	IN	NS	f.tld.sk.g.tld.sk.		3587	IN	A	212.18.248.16g.tld.sk.		3587	IN	AAAA	2a04:2b00:13ee::16