; timestamp: 20220306T211341Z
; source id: tld-query-ua.-in1.ns.ua.
; source locator: in1.ns.ua.
; source IP address: 74.123.224.40
; backup point IP address: 111.42.148.76
; status: success
ua.			3599	IN	NS	in1.ns.ua.ua.			3599	IN	NS	cd1.ns.ua.ua.			3599	IN	NS	bg.ns.ua.ua.			3599	IN	NS	ho1.ns.ua.ua.			3599	IN	NS	pch.ns.ua.ua.			3599	IN	NS	rcz.ns.ua.in1.ns.ua.		3558	IN	A	74.123.224.40in1.ns.ua.		3558	IN	AAAA	2604:ee00:0:101::40