; timestamp: 20220306T211519Z
; source id: tld-query-va.-michael.vatican.va.
; source locator: michael.vatican.va.
; source IP address: 212.77.0.2
; backup point IP address: 111.42.148.76
; status: success
va.			3600	IN	NS	seth.namex.it.va.			3600	IN	NS	osiris.namex.it.va.			3600	IN	NS	va.cctld.authdns.ripe.net.va.			3600	IN	NS	michael.vatican.va.va.			3600	IN	NS	john.vatican.va.va.			3600	IN	NS	dns.nic.it.michael.vatican.va.	3599	IN	A	212.77.0.2michael.vatican.va.	3598	IN	AAAA	2a01:b8:0:1:212:77:0:2