; timestamp: 20220306T201745Z
; source id: tld-query-inc.-d.nic.inc.
; source locator: d.nic.inc.
; source IP address: 212.18.249.137
; backup point IP address: 111.42.148.76
; status: success
inc.			172800	IN	NS	a.nic.inc.inc.			172800	IN	NS	b.nic.inc.inc.			172800	IN	NS	c.nic.inc.inc.			172800	IN	NS	d.nic.inc.d.nic.inc.		3565	IN	A	212.18.249.137d.nic.inc.		3564	IN	AAAA	2a04:2b00:13ff::137