; timestamp: 20220306T201745Z
; source id: tld-query-inc.-a.nic.inc.
; source locator: a.nic.inc.
; source IP address: 194.169.218.137
; backup point IP address: 111.42.148.76
; status: success
inc.			172800	IN	NS	a.nic.inc.inc.			172800	IN	NS	d.nic.inc.inc.			172800	IN	NS	b.nic.inc.inc.			172800	IN	NS	c.nic.inc.a.nic.inc.		3600	IN	A	194.169.218.137a.nic.inc.		151200	IN	AAAA	2001:67c:13cc::1:137