; timestamp: 20220306T211341Z
; source id: tld-query-ua.-bg.ns.ua.
; source locator: bg.ns.ua.
; source IP address: 185.136.97.185
; backup point IP address: 111.42.148.76
; status: success
ua.			3600	IN	NS	ho1.ns.ua.ua.			3600	IN	NS	pch.ns.ua.ua.			3600	IN	NS	rcz.ns.ua.ua.			3600	IN	NS	bg.ns.ua.ua.			3600	IN	NS	cd1.ns.ua.ua.			3600	IN	NS	in1.ns.ua.bg.ns.ua.		3559	IN	A	185.136.97.185bg.ns.ua.		3559	IN	A	185.136.96.185bg.ns.ua.		3559	IN	AAAA	2a06:fb00:1::4:185bg.ns.ua.		3559	IN	AAAA	2a06:fb00:1::2:185