; timestamp: 20220306T212840Z
; source id: tld-query-xn--qxam.-estia.ics.forth.gr.
; source locator: estia.ics.forth.gr.
; source IP address: 139.91.191.3
; backup point IP address: 111.42.148.76
; status: success
xn--qxam.		3599	IN	NS	gr-at.ics.forth.gr.xn--qxam.		3599	IN	NS	gr-d.ics.forth.gr.xn--qxam.		3599	IN	NS	gr-c.ics.forth.gr.xn--qxam.		3599	IN	NS	estia.ics.forth.gr.xn--qxam.		3599	IN	NS	grdns.ics.forth.gr.estia.ics.forth.gr.	3599	IN	A	139.91.191.3estia.ics.forth.gr.	3599	IN	AAAA	2001:648:2c30::191:3