; timestamp: 20220306T204425Z
; source id: tld-query-nr.-ns2.cenpac.net.nr.
; source locator: ns2.cenpac.net.nr.
; source IP address: 202.144.128.200
; backup point IP address: 111.42.148.76
; status: success
nr.			86400	IN	NS	ns1.cenpac.net.nr.nr.			86400	IN	NS	ns2.cenpac.net.nr.nr.			86400	IN	NS	ns0.cenpac.net.nr.nr.			86400	IN	NS	phloem.uoregon.edu.ns2.cenpac.net.nr.	3598	IN	A	202.144.128.200ns2.cenpac.net.nr.	3597	IN	AAAA	2405:d000:0:100::200