; timestamp: 20220306T211341Z
; source id: tld-query-ua.-pch.ns.ua.
; source locator: pch.ns.ua.
; source IP address: 204.61.216.12
; backup point IP address: 111.42.148.76
; status: success
ua.			36036	IN	NS	pch.ns.ua.ua.			36036	IN	NS	cd1.ns.ua.ua.			36036	IN	NS	ho1.ns.ua.ua.			36036	IN	NS	bg.ns.ua.ua.			36036	IN	NS	in1.ns.ua.ua.			36036	IN	NS	rcz.ns.ua.pch.ns.ua.		3558	IN	A	204.61.216.12pch.ns.ua.		3558	IN	AAAA	2001:500:14:6012:ad::1