; timestamp: 20220306T205611Z
; source id: tld-query-run.-v0n2.nic.run.
; source locator: v0n2.nic.run.
; source IP address: 65.22.34.40
; backup point IP address: 111.42.148.76
; status: success
run.			3600	IN	NS	v0n1.nic.run.run.			3600	IN	NS	v2n0.nic.run.run.			3600	IN	NS	v0n0.nic.run.run.			3600	IN	NS	v2n1.nic.run.run.			3600	IN	NS	v0n2.nic.run.run.			3600	IN	NS	v0n3.nic.run.v0n2.nic.run.		3599	IN	A	65.22.34.40v0n2.nic.run.		3599	IN	AAAA	2a01:8840:24::40