; timestamp: 20220306T201745Z
; source id: tld-query-inc.-b.nic.inc.
; source locator: b.nic.inc.
; source IP address: 185.24.64.137
; backup point IP address: 111.42.148.76
; status: success
dig @185.24.64.137 inc. NS

; <<>> DiG 9.16.23 <<>> @185.24.64.137 inc. NS
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

b.nic.inc.		3581	IN	A	185.24.64.137b.nic.inc.		3581	IN	AAAA	2a04:2b00:13cc::1:137