; timestamp: 20220306T200926Z
; source id: tld-query-ge.-ge.hostmaster.ua.
; source locator: ge.hostmaster.ua.
; source IP address: 195.47.253.18
; backup point IP address: 111.42.148.76
; status: success
ge.			14400	IN	NS	ns2.nic.ge.ge.			14400	IN	NS	ns.nic.ge.ge.			14400	IN	NS	ns2.nic.fr.ge.			14400	IN	NS	ge.hostmaster.ua.ge.			14400	IN	NS	ns.uu.net.ge.hostmaster.ua.	3600	IN	A	195.47.253.18ge.hostmaster.ua.	3600	IN	AAAA	2001:67c:258::18