; timestamp: 20220306T201228Z
; source id: tld-query-gr.-gr-c.ics.forth.gr.
; source locator: gr-c.ics.forth.gr.
; source IP address: 194.0.1.25
; backup point IP address: 111.42.148.76
; status: success
gr.			3600	IN	NS	gr-m.ics.forth.gr.gr.			3600	IN	NS	gr-at.ics.forth.gr.gr.			3600	IN	NS	gr-d.ics.forth.gr.gr.			3600	IN	NS	grdns.ics.forth.gr.gr.			3600	IN	NS	estia.ics.forth.gr.gr.			3600	IN	NS	gr-c.ics.forth.gr.gr-c.ics.forth.gr.	950	IN	A	194.0.1.25gr-c.ics.forth.gr.	3600	IN	AAAA	2001:678:4::19